version: "3.4"

services:
  dvd-rental-tdd-example:
    build:
      dockerfile: ./Dockerfile
      context: .
    working_dir: /github.com/gmiejski/dvd-rental-tdd-example
    volumes:
      - .:/github.com/gmiejski/dvd-rental-tdd-example
    ports:
      - "5411:5411"
    env_file:
      - _env
    environment:
      WAIT_FOR_PORTS: database:5432 mongodb:27017
    depends_on:
      - database
      - mongodb
    links:
      - database
      - mongodb
    command: ["go", "run", "main.go"]

  database:
    image: "postgres:9.6-alpine"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=dvd-rental-tdd-example
    ports:
    - "5432:5432"

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    volumes:
    - ./data/db:/data/db
    ports:
    - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  migration:
    image: "brainly/mattes-migrate:3.0.1"
    depends_on:
      - database
    volumes:
      - ./migration:/migration
    env_file:
      - _env
    command: -path /migration -database postgres://postgres:postgres@database:5432/dvd-rental-tdd-example?sslmode=disable -verbose up
